- hosts: proxmox
  vars_files:
    - vault.yml
  roles:
    - snapshot_lxc_containers
    - update_lxc_containers

  tasks:
    - name: Notify on failure
      uri:
        url: "{{ webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body: |
          {
            "content": "Ansible playbook failed for {{ inventory_hostname }}"
          }
        status_code: 204
      when: ansible_failed_result is defined

    - name: Rollback to previous snapshot on failure
      command: pct snapshot {{ item }} rollback pre_update
      when: ansible_failed_result is defined
      loop: "{{ lxc_containers }}"
