- name: Update APT cache inside LXC container
  command: pct exec {{ item }} -- apt update
  loop: "{{ lxc_containers }}"

- name: Upgrade specified packages inside LXC container
  command: pct exec {{ item }} -- apt -y upgrade
  loop: "{{ lxc_containers }}"

- name: Clean up unnecessary packages inside LXC container
  command: pct exec {{ item }} -- apt -y autoremove && apt autoclean
  loop: "{{ lxc_containers }}"

- name: Ensure services are running inside LXC container
  command: pct exec {{ item }} -- systemctl is-active {{ item }} || systemctl start {{ item }}
  loop: "{{ lxc_containers }}"

# Full System Upgrade Logic
- name: Get the current date
  command: date +%d
  register: current_day

- name: Perform full system upgrade if today is the first day of the month
  command: pct exec {{ item }} -- apt -y dist-upgrade && apt autoremove
  when: current_day.stdout == "01"
  retries: 3
  delay: 5
  loop: "{{ lxc_containers }}"

# Add the cron job for Plex cache cleanup
- name: Ensure Plex cache cleanup cron job is present
  cron:
    name: "Plex Cache Cleanup"
    minute: "0"
    hour: "2"
    job: "pct exec 101 -- rm -rf /var/lib/plexmediaserver/Library/Application\\ Support/Plex\\ Media\\ Server/Cache/*"
    user: root
